### PR TITLE
Homework react week#2 Implemented

### PR DESCRIPTION
**Pull request by DiegoRuiz454**

### CODE REVIEW

**Review by piyushpalod — COMMENTED** [review]
There is no change apart from fileName from week 1, can you please check and update PR, or let me know if I missed something.

**Comment by DiegoRuiz454** [comment]
> There is no change apart from fileName from week 1, can you please check and update PR, or let me know if I missed something.

hi piyush..  i dont understand. what you mean? I have not made changes to the code, I just copy the task .js files in this pull request but I have not made any edits

**Comment by piyushpalod** [comment]
Exactly, there is not changes in file and this PR come to me for review but there is nothing to review here.

**Comment by DiegoRuiz454** [comment]
> Exactly, there is not changes in file and this PR come to me for review but there is nothing to review here.

ok i think is because it have the wrong file name i will change

**Pull request closed without merging**
